apiVersion: v1
kind: ReplicationController
metadata:
  name: simplewebapp
spec:
  replicas: 2
  selector:
    app: simplewebapp
  template:
    metadata:
      name: simplewebapp
      labels:
        app: simplewebapp
    spec:
      containers:
      - name: simplewebapp
        image: unit4demo2.azurecr.io/unit4-demo:65
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: chrissecret
