apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: vmcr8-web
  namespace: default
spec:
  rules:
    - host: unit4-web.k8.datalinks.nl
      http:
        paths:
          - backend:
              serviceName: vmcr8-weathermap-web
              servicePort: 8080
            path: /
